"""markov starter words

Revision ID: 11aaa7522e69
Revises: 29fea37b61c2
Create Date: 2015-09-05 22:43:43.310952

"""

# revision identifiers, used by Alembic.
revision = '11aaa7522e69'
down_revision = '29fea37b61c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('markov_starter_words', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'markov_starter_words')
    ### end Alembic commands ###
