"""initial

Revision ID: 14bcd4a81318
Revises: None
Create Date: 2015-08-07 16:09:28.663434

"""

# revision identifiers, used by Alembic.
revision = '14bcd4a81318'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
