"""messages_relationship

Revision ID: 26256f86748e
Revises: 488a6e39839d
Create Date: 2016-02-12 10:31:28.744461

"""

# revision identifiers, used by Alembic.
revision = '26256f86748e'
down_revision = '488a6e39839d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'messages_sender_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(u'messages_sender_fkey', 'messages', u'addresses', [u'sender'], [u'id'])
    ### end Alembic commands ###
