"""markov dict

Revision ID: 29fea37b61c2
Revises: None
Create Date: 2015-08-12 22:03:15.048520

"""

# revision identifiers, used by Alembic.
revision = '29fea37b61c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('markov_dict', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'markov_dict')
    ### end Alembic commands ###
