"""response time

Revision ID: 3abf63ffd5b8
Revises: 2665f0674fa6
Create Date: 2016-02-23 18:35:30.005580

"""

# revision identifiers, used by Alembic.
revision = '3abf63ffd5b8'
down_revision = '2665f0674fa6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_time', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_time')
    ### end Alembic commands ###
