"""databaseimport

Revision ID: 4519697c514a
Revises: 3abf63ffd5b8
Create Date: 2016-03-06 14:22:03.004235

"""

# revision identifiers, used by Alembic.
revision = '4519697c514a'
down_revision = '3abf63ffd5b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_imports')
    ### end Alembic commands ###
