"""avatar_link

Revision ID: 488a6e39839d
Revises: 55d2cf706b70
Create Date: 2016-01-29 15:50:34.967737

"""

# revision identifiers, used by Alembic.
revision = '488a6e39839d'
down_revision = '55d2cf706b70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_link', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_link')
    ### end Alembic commands ###
