"""message_sender

Revision ID: 528d57e92de7
Revises: 26256f86748e
Create Date: 2016-02-17 22:30:33.072282

"""

# revision identifiers, used by Alembic.
revision = '528d57e92de7'
down_revision = '26256f86748e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'messages_sender_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'addresses', ['sender'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(u'messages_sender_fkey', 'messages', u'users', [u'sender'], [u'id'])
    ### end Alembic commands ###
