"""unix_timestamp

Revision ID: 55d2cf706b70
Revises: 11aaa7522e69
Create Date: 2015-12-20 10:28:56.375878

"""

# revision identifiers, used by Alembic.
revision = '55d2cf706b70'
down_revision = '11aaa7522e69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('send_time_unix', sa.String(length=64), nullable=True))
    op.drop_column('users', u'markov_symbol')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'markov_symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('messages', 'send_time_unix')
    ### end Alembic commands ###
